### ISSUE TITLE
Rename heroku app to “snap-it-up”?

### ISSUE THREAD

**Issue by Mr0grog** [codeforamerica/snap-it-up#16]
The heroku app is currently named “snap-status.” Should it be changed to “snap-it-up” to match the new repo name?

Also, @lippytak, @alanjosephwilliams, @daguar, @bengolder drop your Heroku e-mails here or send them to me—rob@robbrackett.com—so I can add you to the app. Or we can move the app to a different account. Or whatever.

**Comment by alanjosephwilliams** [comment]
:+1: done via email

On Thu, Jan 29, 2015 at 7:29 PM, Rob Brackett notifications@github.com
wrote:

> The heroku app is currently named “snap-status.” Should it be changed to
> “snap-it-up” to match the new repo name?
> 
> Also, @lippytak https://github.com/lippytak, @alanjosephwilliams
> https://github.com/alanjosephwilliams, @daguar
> https://github.com/daguar, @bengolder https://github.com/bengolder
> drop your Heroku e-mails here or send them to me—rob@robbrackett.com—so I
> can add you to the app. Or we can move the app to a different account. Or
> whatever.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/codeforamerica/snap-it-up/issues/16.

## 

t:  @alanjosephwilli
p: 817 713 6264

**Comment by bengolder** [comment]
bgolder@codeforamerica.org

**Comment by Mr0grog** [comment]
…do we already have something at snap-it-up.herokuapp.com? The name is taken and it is showing monitoring for some SNAP/benefits portals:

![screen shot 2015-01-29 at 10 54 39 pm](https://cloud.githubusercontent.com/assets/74178/5972183/214ee558-a80a-11e4-90d1-8fc01fff3d6c.png)

**Comment by lippytak** [comment]
lol forgot about that. That was v.0000001 with Pingdom. It is now DEAD so
feel free to hijack the name.

We now have:
- keep-your-balance
- keep-it-clean
- snap-it-up

I dig.

**Comment by Mr0grog** [comment]
> We now have:
> - keep-your-balance
> - keep-it-clean
> - snap-it-up

Sounds like this should be renamed to “keep-it-snappy.” ;)

**Comment by lippytak** [comment]
GENIUS. Do it.

**Comment by alanjosephwilliams** [comment]
It's currently snap-status, which I actually think is the most clear and direct name. Closing.

**Comment by Mr0grog** [comment]
:+1:
