### ISSUE TITLE
Sentry/Airbrake exception monitoring

### ISSUE THREAD

**Issue by bensheldon** [codeforamerica/snap-it-up#18]
Not sure what your favorite flavor of exception monitoring is (or what you're willing to pay for... I spend on Sentey and it's worth it) but you should add one before it goes into production.

**Comment by Mr0grog** [comment]
Actually… this is something all CfA apps should have. Do we have a deal with any services (or something internal set up) for this? If not, somebody at CfA should really get in touch with Sentry or Airbrake about maybe donating access or budget for it.  /cc @daguar

**Comment by monfresh** [comment]
[AppSignal](https://addons.heroku.com/appsignal) is another one you might want to look into so you can compare. I think they all provide the same info, so it would come down to pricing. I've used both Sentry and AppSignal, and didn't feel like Sentry was worth the price.

**Comment by Mr0grog** [comment]
Is AppSignal Rails-specific? If so, it might not really apply here :\

**Comment by daguar** [comment]
> Actually… this is something all CfA apps should have. Do we have a deal with any services (or something internal set up) for this? If not, somebody at CfA should really get in touch with Sentry or Airbrake about maybe donating access or budget for it. /cc @daguar

We do get credits from Heroku, and both Sentry and Airbrake are available as add-ons there, but cc'ing @migurski to get his thoughts.

In general I agree, and think this could be added to the Tech Team checklist for beta/live projects.

**Comment by daguar** [comment]
(If this becomes a core desired thing, it may be worth asking Sentry/Airbrake for a specific donation of credits.)

**Comment by migurski** [comment]
What do they charge? It smells useful to me as well, but a big question is whether you actually want to monitor this long-term. I have a lot of zombie log processes from past projects that terminate in my inbox.

Can you set it up for a period of time and keep it going for only as long as you're actually reading the reports?

**Comment by bensheldon** [comment]
Sentry starts at [$24/month](https://www.getsentry.com/pricing/) for unlimited teams/projects and 25 events/second. I personally pay for my own plan (and point about 8 different apps to it right now)  and would be happy to set up a team for this project if/until other people want to adopt it officially.

**Comment by Mr0grog** [comment]
Closing this since Ben did #38.
