### ISSUE TITLE
Get alert when service comes back up

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/snap-it-up#20]
I want it and a user asked for it :+1:

**Comment by Mr0grog** [comment]
Oh, does statuspage not do that?

(I think I wound up un-subscribing from everything because of all the e-mails I was getting—from both Pingometer and Statuspage. I should probably re-subscribe to Statuspage now that I got that back under control.)

**Comment by bensheldon** [comment]
People can subscribe to alerts thru StatusPage (that's their pricing model: more subscriptions == moar money).

**Comment by Mr0grog** [comment]
I _think_ @lippytak means this is a StatusPage problem, since I believe that’s the only way to publicly get alerts on this stuff right now. Yes?

**Comment by lippytak** [comment]
StatusPage subscribers get alerts whenever an incident is created, edited, or closed (I think).

Right now we have a script that automatically creates an incident when Pingometer shows a site is down, which sends an initial alert. However, we never update or close that incident, so people don't know when the site goes back up.

**Comment by Mr0grog** [comment]
Ah! Makes more sense now. On a related note, should we move that connective tissue into this codebase or continue to keep it separate?

**Comment by pingometer** [comment]
@lippytak @Mr0grog 

I just sent revised code for that webhook script to handle both incident creation and resolution at StatusPage.io using the Pingometer API. Let me know if that'll work.

**Comment by lippytak** [comment]
[New code](https://gist.github.com/lippytak/c5978e631c173c188eb6) courtesy of @pingometer is up and running. I'll close this once I get a successful resolved incident message.
