### ISSUE TITLE
(Some?) Transaction monitors have nameless alerts

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/snap-it-up#21]
Just logging a small @pingometer bug that some/all transaction monitor alerts don't include the monitor name:
![screen shot 2015-02-03 at 7 55 47 pm](https://cloud.githubusercontent.com/assets/2533112/6034946/c2a0adba-abde-11e4-9d03-8288961b4c8b.png)

We're only using these alerts internally so it's not a big deal for us. Check Indiana (monitor ID 54d05a90be653d2e76ff9ce7) as an example.

**Comment by pingometer** [comment]
Thanks! This is fixed now.

**Comment by lippytak** [comment]
It's true! Thanks @pingometer !

![screen shot 2015-02-04 at 2 43 24 pm](https://cloud.githubusercontent.com/assets/2533112/6051353/355d9834-ac7c-11e4-880f-5eafe075f812.png)
