### ISSUE TITLE
Add better Arizona keyword

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/snap-it-up#22]
Right now AZ is getting away with a ton of undetected downtime! So sneaky...

UP looks like this:
![az-up](https://cloud.githubusercontent.com/assets/2533112/6036070/fbfea8fe-abf3-11e4-85e1-e0d8542ce480.png)

Down looks like this:
![screen shot 2015-02-03 at 10 27 38 pm](https://cloud.githubusercontent.com/assets/2533112/6036071/ff95404a-abf3-11e4-89e6-9a31beab290f.png)

So we need to look for some content around that 'get started' button.

**Comment by Mr0grog** [comment]
> Right now AZ is getting away with a ton of undetected downtime!

I’ll say! That notice says they should be down at least 19% of the time!

Side note: seems like it might be potentially useful (or at least interesting) to track known/planned downtime (e.g. that notice on the AZ site says they’re down at least 32 hours/wk) and compare that to the times they are actually down. i.e. how often are they down at “unplanned” times?

To the extent that we want to help or alert social workers and the like when services are down, this kind of info would probably be really helpful as well.

Additionally, such extreme planned downtime would probably be an extremely interesting tidbit to cover in @bengolder’s writeup (#6). Might be interesting to chart downtime/latency by time of day, too…

**Comment by lippytak** [comment]
done

**Comment by Mr0grog** [comment]
Hmmm, I need to get on showing aggregated downtime over 24-hour periods. Curious to see how well their actual and expected downtime line up.
