### ISSUE TITLE
Pingometer is slow

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/snap-it-up#27]
@pingometer just wanted to let you know that loading times (especially for the monitors page) are getting pretty rough.

**Comment by pingometer** [comment]
Thanks for the heads up!

We had a big spike in new users over the past couple days - adding capacity to speed things up.

**Comment by lippytak** [comment]
Congrats! Good problem to have...

**Comment by pingometer** [comment]
It should be about 5x faster soon (tonight/tomorrow).

**Comment by lippytak** [comment]
Much better! Closing :+1:
