### ISSUE TITLE
Add README 

### ISSUE THREAD

**Issue by daguar** [codeforamerica/snap-it-up#28]

**Comment by Mr0grog** [comment]
Hey @daguar, this is a dupe of #1, which has almost exactly the same title.

**Comment by Mr0grog** [comment]
(no offense taken, but maaaybe do a quick scan of the issue list before posting?)

**Comment by daguar** [comment]
Bah, sorry. Was flying through and was frustrated mostly that I couldn't find production. I've added it as the URL for the repo.

**Comment by Mr0grog** [comment]
Cool, no worries. Should the repo URL be http://status.citizenonboard.com/ or http://snap-status.herokuapp.com? Both totally valid, though confusingly separate :P
