### ISSUE TITLE
Seriously really refactor the database insanity

### ISSUE THREAD

**Issue by Mr0grog** [codeforamerica/snap-it-up#31]
The code in `app.rb` and in the tasks right now is just absolutely completely nuts. So much duplicated crap. Need models. Need consolidated logic. (Need time.) Ooof.

**Comment by bensheldon** [comment]
I offered to take a stab at this. I think using Mongo still is fine (until it isn't), so I think extracting out the raw database calls to Mongoid models is the way to go.

**Comment by Mr0grog** [comment]
@bensheldon Have you had a chance to do much with this, or are you still working on just getting some sanity around setup in #32? Just trying to get a sense of where this is so I can avoid stepping on your toes as I continue to poke at other things.
