### ISSUE TITLE
improve map color scheme

### ISSUE THREAD

**Issue by alanjosephwilliams** [codeforamerica/snap-it-up#45]
- decide on appropriate breaks
- adopt a better color scheme that:
  - still communicates a scale of stable <--> unstable
  - avoids conflation with common political maps
  - complements other visual elements of the write up 
  - isn't garish

**Comment by bengolder** [comment]
![screen shot 2015-03-30 at 7 46 21 pm](https://cloud.githubusercontent.com/assets/451510/6911427/7b4c6686-d715-11e4-904e-2e3be53db060.png)
What do you think of this scale?

**Comment by Mr0grog** [comment]
Certainly better than what we’ve got. Everything is so red vs. blue, though.

**Comment by bengolder** [comment]
trying to make it into a threshold scale, these percentages are a bit arbitrary, but 50% should be bad, and if it's going to be bluish it should show a lot of uptime.
![screen shot 2015-03-30 at 8 03 21 pm](https://cloud.githubusercontent.com/assets/451510/6911646/2dbfa90c-d718-11e4-902f-2c2dd7c1960a.png)

**Comment by bengolder** [comment]
less red
![screen shot 2015-03-30 at 8 06 40 pm](https://cloud.githubusercontent.com/assets/451510/6911659/4de34928-d718-11e4-83c1-143319927934.png)

**Comment by Mr0grog** [comment]
I think the way it was before (most bad = 80%) was probably pretty generous. Not sure we need to go all the way down to 50%.

**Comment by bengolder** [comment]
adjusted scale
![screen shot 2015-03-30 at 8 09 44 pm](https://cloud.githubusercontent.com/assets/451510/6911684/beab644c-d718-11e4-9808-7ccd40378228.png)

**Comment by bengolder** [comment]
or
![screen shot 2015-03-30 at 8 10 55 pm](https://cloud.githubusercontent.com/assets/451510/6911694/e4343518-d718-11e4-804f-af547f94e66e.png)

**Comment by Mr0grog** [comment]
:+1:

**Comment by bengolder** [comment]
result:
![screen shot 2015-03-31 at 12 19 27 am](https://cloud.githubusercontent.com/assets/451510/6914062/aa0f2226-d73b-11e4-92cb-7b28cc39a0d1.png)

**Comment by bengolder** [comment]
with different labels. I'd say it looks more dramatic and less readable.
![screen shot 2015-03-31 at 12 22 48 am](https://cloud.githubusercontent.com/assets/451510/6914123/382ccfb8-d73c-11e4-87bc-67f7faa544b2.png)

**Comment by bengolder** [comment]
Here's some more alternatives:

gray to green (bad to working)
![screen shot 2015-03-31 at 12 30 57 am](https://cloud.githubusercontent.com/assets/451510/6914263/993a4938-d73d-11e4-9673-b1bb52399572.png)

orangered to lightgray (bad to nonissue)
![screen shot 2015-03-31 at 12 33 13 am](https://cloud.githubusercontent.com/assets/451510/6914288/c39c6788-d73d-11e4-9ff0-8964ce7c357a.png)

**Comment by Mr0grog** [comment]
FYI @bengolder the data is “correct” now; data from invalid time ranges should be cut out of all uptime calculations.

**Comment by alanjosephwilliams** [comment]
I prefer the last two alternatives to the organ <-> blue (the brain really loses track with that naples yellow ). 

Each serves their respective semantics well—the question I suppose, is should we hold these services to the same standard as commercial sites ("bad to nonissue") or suggest that hey Oklahoma, 92% is pretty good.

I'm open to arguments either way.

**Comment by bensheldon** [comment]
If you're gonna go logarithmicalish rather than differentiating by percentages, it might be more compelling to go by chronological time that's more human centric: 15 min, 1 hour, 8 hours, 1 day, 7 days, etc.

**Comment by bengolder** [comment]
> should we hold these services to the same standard as commercial sites

YES

how about this:
![screen shot 2015-03-31 at 8 49 52 am](https://cloud.githubusercontent.com/assets/451510/6922885/29809d40-d783-11e4-8909-03ea2587ee1e.png)

**Comment by alanjosephwilliams** [comment]
I think that looks great. We should discuss more and further refine in
advance of a public write-up, but I am going to take this image and drop it
into my presentation now. THANK YOU.

On Tue, Mar 31, 2015 at 11:51 AM, Benjamin Golder notifications@github.com
wrote:

> should we hold these services to the same standard as commercial sites
> 
> YES
> 
> how about this:
> [image: screen shot 2015-03-31 at 8 49 52 am]
> https://cloud.githubusercontent.com/assets/451510/6922885/29809d40-d783-11e4-8909-03ea2587ee1e.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/codeforamerica/snap-it-up/issues/45#issuecomment-88140459
> .

## 

t:  @alanjosephwilli
p: 817 713 6264

**Comment by Mr0grog** [comment]
Agree with @alanjosephwilliams; the red -> yellow -> blue is pretty, but much harder to parse.

> should we hold these services to the same standard as commercial sites ("bad to nonissue") or suggest that hey Oklahoma, 92% is pretty good.

I’m tempted to hold them to a _slightly_ relaxed standard from commercial sites (where 95% or even 98% is really bad). Pinning maximum bad at 80-90% here seems reasonable to me. It’s meaningful to be able to clearly say and show, “yeah, some sites are egregiously horrible, but even the middle is not good enough by the standard of someone selling luxury goods. And we’re talking about critical life services.”

That said, you could also show one map in terms of a commercial standard and a second that’s much more generous to pull focus to where the problems are egregious.

**Comment by alanjosephwilliams** [comment]
That's the line I take in the write-up @Mr0grog. Actually @bengolder is it possible to get a version of the map that shows the recalculated data per Rob's recent work?

**Comment by bengolder** [comment]
working on it now, more discussion in slack

**Comment by bengolder** [comment]
![screen shot 2015-03-31 at 9 02 01 am](https://cloud.githubusercontent.com/assets/451510/6923105/a101c618-d784-11e4-829c-4b4d867a497b.png)

**Comment by alanjosephwilliams** [comment]
Great work on this. I think the current color scheme reflects our opinionated take on uptime, and is visually pleasing.
