### ISSUE TITLE
Need to declare a “good after” date for each monitor

### ISSUE THREAD

**Issue by alanjosephwilliams** [codeforamerica/snap-it-up#46]
It looks like when we set up monitoring for Louisiana, we grabbed the redirect URL (dcfs.la.gov:80/index.cfm?md=pagebuilder&tmp=home&pid=407) and began monitoring their error page, rather than the webservice itself.

In any display of the data, we should present Louisiana as having "no data", or something to that effect.

**Comment by daguar** [comment]
I said this on Slack, but +1 to saying "no data" — totally fine for the purposes of this analysis; doesn't affect the overall data.

This also speaks to digging into the details on any extreme cases we want to call out by name — we should doubly verify that our methods are correct and they were/are in fact down.

**Comment by Mr0grog** [comment]
We should actually have a mechanism for noting at what point the data was good on all monitors, since there are some others where a chunk of the historical data was inaccurate (see #8, #9). I’m thinking a field in `public/data/pingometer_monitors.json` called `good_after` with a date.

Side question: for data prior to that date, should we throw it away? I’m thinking we should—it’s inaccurate to begin with and it makes handling things easier (we don’t need special code to filter out events and incidents before the good date and won’t need to be careful to always go that code path).

**Comment by Mr0grog** [comment]
@bensheldon you’ll want to make sure you handle this on the Rails branch, too.

**Comment by alanjosephwilliams** [comment]
I find that to be a sound approach—given the amount of data we have, the
benefits of saving the data are likely outweighed by the costs.

On Mon, Mar 23, 2015 at 10:19 AM, Rob Brackett notifications@github.com
wrote:

> We should actually have a mechanism for noting at what point the data was
> good on all monitors, since there are some others where a chunk of the
> historical data was inaccurate (see #8
> https://github.com/codeforamerica/snap-it-up/issues/8, #9
> https://github.com/codeforamerica/snap-it-up/issues/9). I’m thinking a
> field in public/data/pingometer_monitors.json called good_after with a
> date.
> 
> Side question: for data prior to that date, should we throw it away? I’m
> thinking we should—it’s inaccurate to begin with and it makes handling
> things easier (we don’t need special code to filter out events and
> incidents before the good date and won’t need to be careful to always go
> that code path).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/codeforamerica/snap-it-up/issues/46#issuecomment-85104584
> .

## 

t:  @alanjosephwilli
p: 817 713 6264

**Comment by pingometer** [comment]
If any data is pulled via our API, we're happy to purge the statistics (uptime, response time, etc.) for any monitor prior to a certain date, as well.

**Comment by alanjosephwilliams** [comment]
@Mr0grog These are monitors our manual QA identified as being using approaches that were no longer effective. Date deprecated is the date of the last downtime event before the approach (transaction, URL, expected data) confirmed to be invalid. 
- Louisiana (this issue thread)
  - Approach deprecated: 2/03/15
  - Monitor resolved: 3/23/15
- Indiana (#49)
  - Monitor deprecated: 03/02/15
  - Monitor resolved: _Not yet resolved_.
- Vermont (#52)
  - Monitor deprecated: 03/24/15 
  - Monitor resolved: 3/27/2015

**Comment by Mr0grog** [comment]
The solution for this in code is pretty janky, but it works for now.

**Comment by alanjosephwilliams** [comment]
@Mr0grog closing this for now, since we have implemented a response. Re-open if you feel that the current approach is janky enough to warrant keeping the issue live.
