### ISSUE TITLE
Pingometer API returning `last_event` as JSON string, not object

### ISSUE THREAD

**Issue by Mr0grog** [codeforamerica/snap-it-up#5]
I don’t even.

Don’t know when this change happened in their `/monitors` API. Totally breaks us. I assume it’s a bug on their end (can’t see why it would be intentional), but I guess we should be robust against it?

@pingometer Any chance you can shed some light on this?

**Comment by Mr0grog** [comment]
Well, actually, it’s stringified BSON:

```
"last_event": "{'type': 0, 'utc_timestamp': datetime.datetime(2015, 1, 26, 5, 5, 24, 26000), 'id': ObjectId('54c5cb1419ad8914f902f40f')}"
```

So we can’t just `JSON.parse` it, either.

**Comment by pingometer** [comment]
Thanks for reporting this! We fixed the serialization issue and the
snap-status page appears to be working properly.

**Comment by Mr0grog** [comment]
@pingometer Thanks!
