### ISSUE TITLE
Snapshots broken on Browserstack

### ISSUE THREAD

**Issue by Mr0grog** [codeforamerica/snap-it-up#53]
CfA's Browserstack account no longer has API access (I guess it was trialed in?), so our screenshots are no longer working. Need to fix this.

/cc @migurski?

**Comment by Mr0grog** [comment]
Made a new temp account, which fixes this _for now._ That’s not a permanent fix, though.

**Comment by Mr0grog** [comment]
…and free trial 2 is about to expire.

**Comment by alanjosephwilliams** [comment]
I can charge it to the game and get reimbursed until we have a long term
solution

On Tue, Mar 31, 2015 at 12:17 PM, Rob Brackett notifications@github.com
wrote:

> …and free trial 2 is about to expire.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/codeforamerica/snap-it-up/issues/53#issuecomment-88151276
> .

## 

t:  @alanjosephwilli
p: 817 713 6264

**Comment by alanjosephwilliams** [comment]
I've updated the CfA account—it should now have API access for screenshots. @Mr0grog want to try switching over accounts at your convenience?

**Comment by Mr0grog** [comment]
Doesn’t appear to be working—it needs to be an “automate” plan.

**Comment by alanjosephwilliams** [comment]
got it. will upgrade now.

On Tue, Apr 7, 2015 at 9:02 PM, Rob Brackett notifications@github.com
wrote:

> Doesn’t appear to be working—it needs to be an “automate” plan.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/codeforamerica/snap-it-up/issues/53#issuecomment-90797138
> .

## 

t:  @alanjosephwilli
p: 817 713 6264

**Comment by alanjosephwilliams** [comment]
done.

On Wed, Apr 8, 2015 at 5:15 PM, Alan Williams alanjosephwilliams@gmail.com
wrote:

> got it. will upgrade now.
> 
> On Tue, Apr 7, 2015 at 9:02 PM, Rob Brackett notifications@github.com
> wrote:
> 
> > Doesn’t appear to be working—it needs to be an “automate” plan.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/codeforamerica/snap-it-up/issues/53#issuecomment-90797138
> > .
> 
> ## 
> 
> t:  @alanjosephwilli
> p: 817 713 6264

## 

t:  @alanjosephwilli
p: 817 713 6264

**Comment by Mr0grog** [comment]
Updated in prod and works.
