### ISSUE TITLE
Map of February uptime from local data

### ISSUE THREAD

**Issue by alanjosephwilliams** [codeforamerica/snap-it-up#54]
@Mr0grog My understanding is that we are now visualizing our maps from local data per #51 

For the presentation (which I need to turn in tomorrow AM at the latest), I want to include at least one map.

I could do a static shot of the current "Uptime over the past week" map, which has data good enough to include with generalized statements about uptime. However, I was thinking that a map for the month of February might make a more compelling point.

Would generating that map—with existing styles, labels, etc—have a low enough LOE to fit on your plate today?

**Comment by Mr0grog** [comment]
Probably can’t do it until tonight, but it’s definitely not hard. Note also the issues in #55. It doesn’t matter too much for this since we can’t change things historically, but…

(Also, I need to solve #46 first. It doesn’t look you ever added the bad date ranges to the JSON. Can you do that? Or at least list them all explicitly in that issue?)

**Comment by alanjosephwilliams** [comment]
Doing so now. If at all possible to ship this with the presentation
tomorrow AM east coast time, that would be profoundly awesome. Thank you
@mr0grog!

On Mon, Mar 30, 2015 at 12:51 PM, Rob Brackett notifications@github.com
wrote:

> Probably can’t do it until tonight, but it’s definitely not hard. Note
> also the issues in #55
> https://github.com/codeforamerica/snap-it-up/issues/55. It doesn’t
> matter too much for this since we can’t change things historically, but…
> 
> (Also, I need to solve #46
> https://github.com/codeforamerica/snap-it-up/issues/46 first. It
> doesn’t look you ever added the bad date ranges to the JSON. Can you do
> that? Or at least list them all explicitly in that issue?)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/codeforamerica/snap-it-up/issues/54#issuecomment-87747918
> .

## 

t:  @alanjosephwilli
p: 817 713 6264

**Comment by Mr0grog** [comment]
I thought the presentation was Wednesday!

**Comment by alanjosephwilliams** [comment]
It is indeed, and if I need to swap out slides last minute, I can probably
do that.

On Mon, Mar 30, 2015 at 1:41 PM, Rob Brackett notifications@github.com
wrote:

> I thought the presentation was Wednesday!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/codeforamerica/snap-it-up/issues/54#issuecomment-87767039
> .

## 

t:  @alanjosephwilli
p: 817 713 6264

**Comment by alanjosephwilliams** [comment]
but slides are due at noon EST tomorrow at the latest, since its a pretty
high falutin' conference.

On Mon, Mar 30, 2015 at 1:47 PM, Alan Williams <alanjosephwilliams@gmail.com

> wrote:
> 
> It is indeed, and if I need to swap out slides last minute, I can probably
> do that.
> 
> On Mon, Mar 30, 2015 at 1:41 PM, Rob Brackett notifications@github.com
> wrote:
> 
> > I thought the presentation was Wednesday!
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/codeforamerica/snap-it-up/issues/54#issuecomment-87767039
> > .
> 
> ## 
> 
> t:  @alanjosephwilli
> p: 817 713 6264

## 

t:  @alanjosephwilli
p: 817 713 6264

**Comment by Mr0grog** [comment]
@alanjosephwilliams This can be closed now, right?

**Comment by alanjosephwilliams** [comment]
@Mr0grog indeed. @bengolder produces an excellent map of downtime for the last 30 days (rather than the month of February) in advance of the presentation last week—which went over very well.
