### ISSUE TITLE
Browserstack screenshots hold connection until timeout

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/snap-it-up#62]
@wpietri observed some weird behavior with how we're taking screenshots with Browserstack:

> william [2:21 PM] 
> I can't disable them. But they currently hold the connection open after the screenshot until the timeout.
> I'd like them to close after they're done, freeing up resources for some automated testing I'm doing.

@Mr0grog can you look into this when you have time?

**Comment by wpietri** [comment]
Ah, thanks, being able to see the code helps. It looks like @Mr0grog already tried to fix this:

https://github.com/codeforamerica/snap-it-up/commit/4e77ab6259bc744ba747ca7b42ed6a0a543642ab

But BrowserStack is still showing things as continuing to run, so either this code isn't deployed or it isn't having the intended effect.

**Comment by Mr0grog** [comment]
Looks like this was coming from the `rails` branch and appears to be solved with 63cf08b7f7b97899a7a7e9b671d4e195eab27ac7

I’ve also added project names to both `master` and `rails` branches so we can see what’s going on in Browserstack.
