### ISSUE TITLE
Figure out how to keyword check Kansas

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/snap-it-up#8]
https://kscapportalp.dcf.ks.gov/client/start.swe?

Then look at the source :/

**Comment by daguar** [comment]
Holy shit: that's amazing.

On Tue, Jan 27, 2015 at 5:59 PM, Jake Solomon notifications@github.com
wrote:

> https://kscapportalp.dcf.ks.gov/client/start.swe?
> 
> Then look at the source :/
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/codeforamerica/snap-it-up/issues/8.

## 

Dave Guarino
Engineer, Health
(2013 Fellowship alumnus)
Code for America http://www.codeforamerica.org/
dave@codeforamerica.org
LinkedIn http://www.linkedin.com/in/daveguarino/ | GitHub
https://github.com/daguar/

**Comment by lippytak** [comment]
Done. Again @Mr0grog I had to create a new Kansas monitor to do this (ID=54d05e25be653d2c21ff9cf6)

**Comment by Mr0grog** [comment]
@lippytak Still works since we are matching by hostname instead of ID, but it would be great if you just updated `public/data/pingometer_monitors.json`, too!
